language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - easy_install Cython

install: 
  - python setup.py build_ext -i

script:
  - nosetests --with-doctest tess
