language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - easy_install Cython

install: 
  - (cd docs && pip install -r requirements.txt)
  - python setup.py build_ext -i

script:
  - nosetests --with-doctest tess
  - (cd docs && make doctests)